name: Test on commits

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  per_os_tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc

    steps:
    - name: Checkout sources
      uses: actions/checkout@v2

    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
        target: ${{ matrix.target }}

    - name: Version
      run: |
        rustup --version
        cargo --version
        cargo clippy --version

    - uses: Swatinem/rust-cache@v1
    - uses: extractions/setup-just@v1

    - name: Build
      env:
        TARGET: ${{ matrix.target }}
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --target ${{ matrix.target }}

    - name: Unit Test
      env:
        TARGET: ${{ matrix.target }}
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --target ${{ matrix.target }}

    - name: Install Tools for Tests
      continue-on-error: true
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        sudo apt-get install bash zsh fish tcsh
        wget -q https://github.com/nushell/nushell/releases/download/0.31.0/nu_0_31_0_linux.tar.gz
        tar xf nu_0_31_0_linux.tar.gz
        cp nu_0_31_0_linux/nushell-0.31.0/* $HOME/.local/bin

    - name: Install Tools for Tests
      continue-on-error: true
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        cinst -y clink cmder
        Invoke-WebRequest -Uri https://github.com/nushell/nushell/releases/download/0.31.0/nu_0_31_0_windows.zip -OutFile nu_0_31_0_windows.zip
        # Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
        Expand-Archive -LiteralPath nu_0_31_0_windows.zip -DestinationPath .

    - name: Install Tools for Tests
      continue-on-error: true
      if: ${{ matrix.os == 'macos-latest' }}
      run: |
        brew install bash zsh fish tcsh
        wget -q https://github.com/nushell/nushell/releases/download/0.31.0/nu_0_31_0_macOS.zip

    - name: Integration Test
      env:
        TARGET: ${{ matrix.target }}
      if: ${{ matrix.os == 'windows-latest' }}
      run: just all_windows

    - name: Integration Test
      env:
        TARGET: ${{ matrix.target }}
      if: ${{ matrix.os != 'windows-latest' }}
      run: just all
